- platform: flux
  lights:
    - light.Kitchen_Ceiling
  name: Fluxer
  start_time: '7:00'
  stop_time: '23:00'
  start_colortemp: 4000
  sunset_colortemp: 3000
  stop_colortemp: 1900
  brightness: 200
  disable_brightness_adjust: True
  mode: xy
  transition: 30
  interval: 60

- platform: broadlink
  host: 192.168.1.76
  mac: '34:EA:34:88:F7:2A'
  timeout: 15
  switches:
    # Will work on most Phillips TVs:
    tv_phillips:
      friendly_name: "Phillips Tv Power"
      command_on: 'JgAcAB0dHB44HhweGx4cHR06HB0cHhwdHB8bHhwADQUAAAAAAAAAAAAAAAA='
      command_off: 'JgAaABweOR4bHhwdHB4dHRw6HhsdHR0dOTocAA0FAAAAAAAAAAAAAAAAAAA='